### ISSUE TITLE
about the file named "feature.embedding"

### ISSUE THREAD

**Issue by ACPMMD** [KaiQiangSong/struct_infused_summ#2]
How is the vector in the file named “feature.embedding”  generated, is it randomly initialized?

**Comment by KaiQiangSong** [comment]
@cuipi254645734 
See this code line:
https://github.com/KaiQiangSong/struct_infused_summ/blob/master/vocabulary/vocabulary.py#L171
It is randomly generate with a scale 0.01.
```python
def random_weights(n_in,n_out, scale = None):
    if scale is None:
        scale = np.sqrt(2.0 / (n_in + n_out))
    W = scale * np.random.randn(n_in,n_out)
return W.astype('float32')
```
